[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''

[[redirects]]
  from = "/project3/*"
  to = "https://rainbow-frangollo-f398cb.netlify.app/:splat"
  status = 200