[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''

[[redirects]]
  from = "/project4/*"
  to = "https://frolicking-melba-30227a.netlify.app/project4/:splat"
  status = 200

[[redirects]]
  from = "/project3/*"
  to = "https://rainbow-frangollo-f398cb.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/project2/*"
  to = "https://gorgeous-figolla-ee9b84.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/project1/*"
  to = "https://endearing-fenglisu-0d38bc.netlify.app/:splat"
  status = 200